#!/bin/sh
if [ "${UID}" != 0 ]; then SUDO="sudo "; else SUDO=""; fi

#if test \! -c /dev/rtai_shm; then
#	$SUDO mknod -m 666 /dev/rtai_shm c 10 254
#fi
#for n in `seq 0 9`; do
#	f=/dev/rtf$n
#	if test \! -c $f; then
#		$SUDO mknod -m 666 $f c 150 $n
#	fi
#done

insmod=/sbin/insmod
rmmod=/sbin/rmmod
m3ko=/lib/modules/$(uname -r)/extra/m3ec.ko
MODULES=/usr/realtime/modules

# May not be necessary
$SUDO $rmmod lp
$SUDO $rmmod parport_pc
$SUDO $rmmod ppdev
$SUDO $rmmod parport

if [ -f $MODULES/rtai_smi.ko ]
then
  sync
  $SUDO $insmod $MODULES/rtai_smi.ko;
  echo 'Inserting rtai_smi'
fi


#sync paranoia might be useful
echo 'Inserting rtai_hal'
sync
$SUDO $insmod $MODULES/rtai_hal.ko IsolCpusMask=0;
echo 'Inserting rtai_sched'
sync
$SUDO $insmod $MODULES/rtai_sched.ko;
echo 'Inserting rtai_sem'
sync
$SUDO $insmod $MODULES/rtai_sem.ko;
echo 'Inserting rtai_shm'
sync
$SUDO $insmod $MODULES/rtai_shm.ko;

sync
sync
$SUDO $insmod $m3ko;
echo 'Inserting m3ec'


